-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type (currently only "toggle", "progressive" and "consumable" but feel free to expand for your needs!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua

-- Functions to turn Soul Blazer IDs into AP item IDs
AP_ID_OFFSET_SOUL = 300

local function apIdForItem(localId)
  return AP_BASE_ID + localId
end

local function apIdForLairRelease(localId)
  return AP_BASE_ID + AP_ID_OFFSET_LAIR + localId
end

local function apIdForSoul(localId)
  return AP_BASE_ID + AP_ID_OFFSET_SOUL + localId
end

ITEM_MAPPING = {
  [apIdForItem(0x01)] = {"lifesword", "toggle"},
  [apIdForItem(0x02)] = {"psychosword", "toggle"},
  [apIdForItem(0x03)] = {"criticalsword", "toggle"},
  [apIdForItem(0x04)] = {"luckyblade", "toggle"},
  [apIdForItem(0x05)] = {"zantetsu", "toggle"},
  [apIdForItem(0x06)] = {"spirit", "toggle"},
  [apIdForItem(0x07)] = {"recoverysword", "toggle"},
  [apIdForItem(0x08)] = {"soulblade", "toggle"},

  [apIdForItem(0x09)] = {"ironarmor", "toggle"},
  [apIdForItem(0x0A)] = {"icearmor", "toggle"},
  [apIdForItem(0x0B)] = {"bubblearmor", "toggle"},
  [apIdForItem(0x0C)] = {"magicarmor", "toggle"},
  [apIdForItem(0x0D)] = {"mysticarmor", "toggle"},
  [apIdForItem(0x0E)] = {"lightarmor", "toggle"},
  [apIdForItem(0x0F)] = {"elementalmail", "toggle"},
  [apIdForItem(0x10)] = {"soularmor", "toggle"},

  [apIdForItem(0x11)] = {"flameball", "toggle"},
  [apIdForItem(0x12)] = {"lightarrow", "toggle"},
  [apIdForItem(0x13)] = {"magicflare", "toggle"},
  [apIdForItem(0x14)] = {"rotator", "toggle"},
  [apIdForItem(0x15)] = {"sparkbomb", "toggle"},
  [apIdForItem(0x16)] = {"flamepillar", "toggle"},
  [apIdForItem(0x17)] = {"tornado", "toggle"},
  [apIdForItem(0x18)] = {"phoenix", "toggle"},

  [apIdForItem(0x19)] = {"goatfood", "toggle"},
  [apIdForItem(0x1A)] = {"harpstring", "toggle"},
  [apIdForItem(0x1B)] = {"pass", "toggle"},
  [apIdForItem(0x1C)] = {"dreamrod", "toggle"},
  [apIdForItem(0x1D)] = {"leobrush", "toggle"},
  [apIdForItem(0x1E)] = {"greenleaves", "toggle"},
  [apIdForItem(0x1F)] = {"moleribbon", "toggle"},
  [apIdForItem(0x20)] = {"bigpearl", "toggle"},
  [apIdForItem(0x21)] = {"mermaidtears", "toggle"},
  [apIdForItem(0x22)] = {"mushroomshoes", "toggle"},

  [apIdForItem(0x23)] = {"mobilekey", "toggle"},
  [apIdForItem(0x24)] = {"thunderring", "toggle"},
  [apIdForItem(0x25)] = {"seeds", "toggle"},
  [apIdForItem(0x26)] = {"actleaves", "toggle"},
  [apIdForItem(0x27)] = {"doorkey", "toggle"},
  [apIdForItem(0x28)] = {"platinumcard", "toggle"},
  [apIdForItem(0x29)] = {"vipcard", "toggle"},
  [apIdForItem(0x2A)] = {"emblema", "toggle"},
  [apIdForItem(0x2B)] = {"emblemb", "toggle"},
  [apIdForItem(0x2C)] = {"emblemc", "toggle"},

  [apIdForItem(0x2D)] = {"emblemd", "toggle"},
  [apIdForItem(0x2E)] = {"embleme", "toggle"},
  [apIdForItem(0x2F)] = {"emblemf", "toggle"},
  [apIdForItem(0x30)] = {"emblemg", "toggle"},
  [apIdForItem(0x31)] = {"emblemh", "toggle"},
  [apIdForItem(0x32)] = {"redhotmirror", "toggle"},
  [apIdForItem(0x33)] = {"redhotball", "toggle"},
  [apIdForItem(0x34)] = {"redhotrod", "toggle"},
  [apIdForItem(0x35)] = {"powerbracelet", "toggle"},
  [apIdForItem(0x36)] = {"shieldbracelet", "toggle"},

  [apIdForItem(0x37)] = {"superbracelet", "toggle"},
  [apIdForItem(0x38)] = {"medicalherb", "toggle"},
  [apIdForItem(0x39)] = {"strangebottle", "toggle"},
  [apIdForItem(0x3A)] = {"brownstone", "toggle"},
  [apIdForItem(0x3B)] = {"greenstone", "toggle"},
  [apIdForItem(0x3C)] = {"bluestone", "toggle"},
  [apIdForItem(0x3D)] = {"silverstone", "toggle"},
  [apIdForItem(0x3E)] = {"purplestone", "toggle"},
  [apIdForItem(0x3F)] = {"blackstone", "toggle"},
  [apIdForItem(0x40)] = {"magicbell", "toggle"},

  [apIdForLairRelease(2)] = {"w1villagechiefhouse", "toggle"},
  [apIdForLairRelease(6)] = {"w1toolshopowner", "toggle"},
  [apIdForLairRelease(8)] = {"w1bridgeguard", "toggle"},
  [apIdForLairRelease(9)] = {"w1villagechief", "toggle"},
  [apIdForLairRelease(13)] = {"w1ivytwochests", "toggle"},
  [apIdForLairRelease(14)] = {"w1watermillkeeper", "toggle"},
  [apIdForLairRelease(15)] = {"w1goatpen", "toggle"},
  [apIdForLairRelease(16)] = {"w1lisa", "toggle"},
  [apIdForLairRelease(18)] = {"w1architect", "toggle"},
  [apIdForLairRelease(19)] = {"w1ivysoutheast", "toggle"},
  [apIdForLairRelease(22)] = {"w1teddy", "toggle"},
  [apIdForLairRelease(26)] = {"w1leoshouse", "toggle"},
  [apIdForLairRelease(34)] = {"w1sleepytulip", "toggle"},
  [apIdForLairRelease(37)] = {"w1boyguardinghideout", "toggle"},
  [apIdForLairRelease(43)] = {"w1ivyemblema", "toggle"},
  [apIdForLairRelease(44)] = {"w1ivyhideoutcrystal", "toggle"},

  [apIdForLairRelease(55)] = {"w2bird", "toggle"},
  [apIdForLairRelease(63)] = {"w2woodstindog", "toggle"},
  [apIdForLairRelease(64)] = {"w2monmo", "toggle"},
  [apIdForLairRelease(65)] = {"w2squirrelroommate", "toggle"},
  [apIdForLairRelease(67)] = {"w2squirrelhungry", "toggle"},
  [apIdForLairRelease(73)] = {"w2molesoul", "toggle"},
  [apIdForLairRelease(74)] = {"w2woodstindeer", "toggle"},
  [apIdForLairRelease(78)] = {"w2crocodileisland", "toggle"},
  [apIdForLairRelease(80)] = {"w2guardian", "toggle"},
  [apIdForLairRelease(81)] = {"w2holesleepystump", "toggle"},
  [apIdForLairRelease(88)] = {"w2squirrelsleepy", "toggle"},
  [apIdForLairRelease(91)] = {"w2crocodilegraveyard", "toggle"},
  [apIdForLairRelease(93)] = {"w2woodstinsquirrel", "toggle"},
  [apIdForLairRelease(97)] = {"w2sleepybird", "toggle"},
  [apIdForLairRelease(98)] = {"w2holeoutside", "toggle"},
  [apIdForLairRelease(99)] = {"w2deer", "toggle"},
  [apIdForLairRelease(111)] = {"w2crocodiledeer", "toggle"},
  [apIdForLairRelease(114)] = {"w2moleoutside", "toggle"},

  [apIdForLairRelease(132)] = {"w3mermaidnortheast", "toggle"},
  [apIdForLairRelease(138)] = {"w3mermaidwestguard", "toggle"},
  [apIdForLairRelease(140)] = {"w3dolphinprisonbreak", "toggle"},
  [apIdForLairRelease(141)] = {"w3statueblester", "toggle"},
  [apIdForLairRelease(142)] = {"w3mermaidgift", "toggle"},
  [apIdForLairRelease(143)] = {"w3lue", "toggle"},
  [apIdForLairRelease(153)] = {"w3mermaiddanceleader", "toggle"},
  [apIdForLairRelease(155)] = {"w3dolphinnortheast", "toggle"},
  [apIdForLairRelease(157)] = {"w3statuerockbird", "toggle"},
  [apIdForLairRelease(161)] = {"w3mermaidhouse", "toggle"},
  [apIdForLairRelease(171)] = {"w3statuedurean", "toggle"},
  [apIdForLairRelease(177)] = {"w3angelfishsoul", "toggle"},
  [apIdForLairRelease(181)] = {"w3mermaidwesthouse", "toggle"},
  [apIdForLairRelease(182)] = {"w3mermaidqueen", "toggle"},
  [apIdForLairRelease(185)] = {"w3statueghostship", "toggle"},
  [apIdForLairRelease(187)] = {"w3dolphinsleepy", "toggle"},
  [apIdForLairRelease(193)] = {"w3dolphinwest", "toggle"},

  [apIdForLairRelease(204)] = {"w4boywest", "toggle"},
  [apIdForLairRelease(211)] = {"w4grandpanorthwest", "toggle"},
  [apIdForLairRelease(214)] = {"w4nome", "toggle"},
  [apIdForLairRelease(221)] = {"w4sleepymushroom", "toggle"},
  [apIdForLairRelease(225)] = {"w4dancinggrandma2", "toggle"},
  [apIdForLairRelease(230)] = {"w4dancinggrandma1", "toggle"},
  [apIdForLairRelease(232)] = {"w4snail", "toggle"},
  [apIdForLairRelease(233)] = {"w4boygift", "toggle"},
  [apIdForLairRelease(238)] = {"w4mushroomsouth", "toggle"},
  [apIdForLairRelease(242)] = {"w4girl", "toggle"},
  [apIdForLairRelease(248)] = {"w4grandpasouthwest", "toggle"},
  [apIdForLairRelease(252)] = {"w4grandpalake", "toggle"},
  [apIdForLairRelease(254)] = {"w4grandpalune", "toggle"},
  [apIdForLairRelease(255)] = {"w4grandpanome", "toggle"},
  [apIdForLairRelease(259)] = {"w4mountainking", "toggle"},

  [apIdForLairRelease(265)] = {"w5plantmice", "toggle"},
  [apIdForLairRelease(268)] = {"w5drawers1st", "toggle"},
  [apIdForLairRelease(269)] = {"w5cat2", "toggle"},
  [apIdForLairRelease(274)] = {"w5doorentry", "toggle"},
  [apIdForLairRelease(276)] = {"w5cat1", "toggle"},
  [apIdForLairRelease(282)] = {"w5doorsouthwest", "toggle"},
  [apIdForLairRelease(286)] = {"w5model1", "toggle"},
  [apIdForLairRelease(288)] = {"w5doormodel", "toggle"},
  [apIdForLairRelease(290)] = {"w5steps2nd", "toggle"},
  [apIdForLairRelease(294)] = {"w5sleepycat", "toggle"},
  [apIdForLairRelease(297)] = {"w5mouseoutside", "toggle"},
  [apIdForLairRelease(303)] = {"w5marie", "toggle"},
  [apIdForLairRelease(316)] = {"w5mouseinside", "toggle"},
  [apIdForLairRelease(322)] = {"w5doorsoul", "toggle"},
  [apIdForLairRelease(325)] = {"w5model2", "toggle"},
  [apIdForLairRelease(331)] = {"w5stepsattic", "toggle"},
  [apIdForLairRelease(332)] = {"w5drawersattic", "toggle"},
  [apIdForLairRelease(333)] = {"w5plantmodel", "toggle"},
  [apIdForLairRelease(341)] = {"w5stepsbasement", "toggle"},

  [apIdForLairRelease(353)] = {"w6sleepysoldier", "toggle"},
  [apIdForLairRelease(359)] = {"w6singer", "toggle"},
  [apIdForLairRelease(365)] = {"w6soldierleft", "toggle"},
  [apIdForLairRelease(366)] = {"w6soldierdok", "toggle"},
  [apIdForLairRelease(368)] = {"w6soldierconcert", "toggle"},
  [apIdForLairRelease(377)] = {"w6soldiersoul", "toggle"},
  [apIdForLairRelease(383)] = {"w6queen", "toggle"},
  [apIdForLairRelease(385)] = {"w6soldieroct", "toggle"},
  [apIdForLairRelease(386)] = {"w6soldierright", "toggle"},
  [apIdForLairRelease(387)] = {"w6leo", "toggle"},
  [apIdForLairRelease(391)] = {"w6maid", "toggle"},
  [apIdForLairRelease(396)] = {"w6soldiercastle", "toggle"},
  [apIdForLairRelease(405)] = {"w6king", "toggle"},

  [apIdForSoul(0)] = {"soulmagician", "toggle"},
  [apIdForSoul(1)] = {"soullight", "toggle"},
  [apIdForSoul(2)] = {"soulshield", "toggle"},
  [apIdForSoul(3)] = {"souldetection", "toggle"},
  [apIdForSoul(4)] = {"soulreality", "toggle"},

}

-- [00000] = {"toggle", "toggle"},
-- [00001] = {"progressive", "progressive"},
-- [00002] = {"consumable", "consumable"},
-- [00003] = {"progressive_toggle", "progressive"} -- progressive_toggle should work with the progressive type but might need additional code to work for your needs
