ScriptHost:LoadScript( "scripts/autotracking/chests.lua" )
ScriptHost:LoadScript( "scripts/autotracking/standard-lairlookup.lua" )
ScriptHost:LoadScript( "scripts/autotracking/lairs.lua" )
-- ScriptHost:LoadScript( "scripts/autotracking/standard-misc.lua" )
ScriptHost:LoadScript( "scripts/autotracking/mapswitch_simple.lua" )
