ScriptHost:LoadScript( "scripts/autotracking/chests.lua" )
ScriptHost:LoadScript( "scripts/autotracking/archipelago-lairlookup.lua" )
ScriptHost:LoadScript( "scripts/autotracking/lairs.lua" )
ScriptHost:LoadScript( "scripts/autotracking/archipelago-misc.lua" )
ScriptHost:LoadScript( "scripts/autotracking/mapswitch_simple.lua" )
